version: "3"
services:
  reverse-proxy:
    build:
      context: ./frontend
      dockerfile: ./Dockerfile
    restart: unless-stopped
    ports:
      - "3000:80"
    volumes:
      - ./frontend/Caddyfile:/etc/caddy/Caddyfile:ro
      - caddy_data:/data
      - caddy_config:/config

  app:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    tty: true
    environment:
      PORT: 8000
      SESSION_SECRET: my-super-secret-session
      DB_HOST: db
      DB_PORT: 3306
      DB_USER: sysdes
      DB_PASSWORD: sysdes
      DB_NAME: sysdes_todolist_db
    volumes:
      - .:/go/src/app
    expose:
      - "8000"
    depends_on:
      - db

  db:
    build:
      context: ./docker/db
      dockerfile: Dockerfile
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: sysdes_todolist_db
      MYSQL_USER: sysdes
      MYSQL_PASSWORD: sysdes
      TZ: 'Asia/Tokyo'
    volumes:
      - ./docker/db/sql:/docker-entrypoint-initdb.d
      - ./docker/db/data:/var/lib/mysql
    ports:
      - "3306:3306"

volumes:
  caddy_data:
  caddy_config:
